[profile.default]
src = "src"
out = "foundry-out"
script = "script"
test = "test"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
auto_detect_remappings = true
bytecode_hash = "none"
gas_limit = "3000000000"

fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" }, 
    { access = "read", path = "foundry-out/" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" }
]




remappings = [
    "@self/=node_modules/@selfxyz/contracts/contracts/",
    "@cryptoalgebra/default-plugin/=lib/plugins-monorepo/packages/default-plugin/",
    "@cryptoalgebra/abstract-plugin/=lib/plugins-monorepo/packages/abstract-plugin/",
    "@cryptoalgebra/dynamic-fee-plugin/=lib/plugins-monorepo/packages/dynamic-fee/",
    "@cryptoalgebra/farming-proxy-plugin/=lib/plugins-monorepo/packages/farming-proxy/",
    "@cryptoalgebra/volatility-oracle-plugin/=lib/plugins-monorepo/packages/volatility-oracle/",
    "@cryptoalgebra/integral-core/=lib/Algebra/src/core/",
    "@cryptoalgebra/integral-periphery/=lib/Algebra/src/periphery/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-v5/=lib/openzeppelin-contracts-v5/",
    "forge-std/=lib/forge-std/src/",
    "mento-core/=lib/mento-core/",
    "mento-deployment/=lib/mento-deployment/",
    "mento-std/=lib/mento-std/",
    "mento-router/=lib/mento-router/",
    "governance-tests/=lib/governance-tests/",
    "oracle-v2-playground/=lib/oracle-v2-playground/",
    "@Cyfrin/foundry-devops/=lib/foundry-devops/src/"
]

[rpc_endpoints]
celo = "https://rpc.celo-community.org"
celo_alfajores = "https://alfajores-rpc.celo-community.org"
celo_baklava = "https://baklava-rpc.celo-community.org"

[etherscan]
celo = { key = "${CELO_API_KEY}" }
celo_alfajores = { key = "${CELO_API_KEY}" }
celo_baklava = { key = "${CELO_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
